### PR TITLE
fix: add localhost to asset canister's CSP

### PR DESCRIPTION
**Pull request by mraszyk**
This MR adds `http://localhost:*` as `connect-src` into the asset canister's CSP. This will enable browsing the asset canister at `http://<canister-id>.localhost:<port>` in most browsers.

### CODE REVIEW

**Review by smallstepman — APPROVED** [review]

**Comment by smallstepman** [comment]
I wonder if we should also add `https://localhost` - remember the safari issue that has been recently discussed @adamspofford-dfinity @krpeacock ?

**Comment by krpeacock** [comment]
It wouldn't hurt

**Comment by smallstepman** [comment]
extending e2e test with multiple schemas (`localhost:`, `127...`, `<can-id>.localhost:`) would also strengthen the reliability of FE canister for local deployments (future work necessary for testing mainnet deployments)
- https://github.com/dfinity/sdk/actions/runs/7166344405/job/19521096556#step:7:146
- https://github.com/dfinity/sdk/blob/master/.github/workflows/e2e.yml#L186-L190

@mraszyk lemme know if you want to contribute on that front as well

**Comment by mraszyk** [comment]
> extending e2e test with multiple schemas (`localhost:`, `127...`, `<can-id>.localhost:`) would also strengthen the reliability of FE canister for local deployments (future work necessary for testing mainnet deployments)
> 
> * https://github.com/dfinity/sdk/actions/runs/7166344405/job/19521096556#step:7:146
> * https://github.com/dfinity/sdk/blob/master/.github/workflows/e2e.yml#L186-L190
> 
> @mraszyk lemme know if you want to contribute on that front as well

I wouldn't mind if you could please update the e2e tests.

**Comment by mraszyk** [comment]
@smallstepman Do you want to extend e2e tests as part of this MR or do you have a separate ticket for that?

**Pull request merged**
