### PR TITLE
refactor: standardize indentation for e2e test scripts

### PR DESCRIPTION
**Pull request by ericswanson-dfinity**
# Description

We have some e2e test scripts that use 4-space indentation, and others that have 2-space indentation.  Within some e2e test script files, we have some tests that use 4-space indentation and others that use 2-space indentation.

This PR changes all e2e test scripts to use 2-space indentation, for consistency and not having to wonder what to use when adding a new test.

# How Has This Been Tested?

CI will cover it

### CODE REVIEW

**Comment by krpeacock** [comment]
I'm down with the consistency, but is there any way we could enforce this rule going forward with linting?

**Comment by lwshang** [comment]
How do you format these bats scripts?
I just tried `shfmt` which doesn't work.

**Comment by ericswanson-dfinity** [comment]
> I'm down with the consistency, but is there any way we could enforce this rule going forward with linting?

We could with [super-linter](https://github.com/super-linter/super-linter) if shfmt worked here, but it doesn't.  (And see draft PR https://github.com/dfinity/sdk/pull/3293 to add super-linter)

```
$ shfmt -i 2 e2e/tests-dfx/assetscanister.bash 
e2e/tests-dfx/assetscanister.bash:57:1: "}" can only be used to close a block
```

It would be nice, but it's beyond the scope of this PR to add CI enforcement.

**Comment by lwshang** [comment]
Found a possible solution:
https://github.com/bats-core/bats-core/blob/f7defb94362f2053a3e73d13086a167448ea9133/docs/source/writing-tests.md#comment-syntax

`bats` has valid bash alternative syntax. Should we consider using it?

**Comment by ericswanson-dfinity** [comment]
> Found a possible solution: https://github.com/bats-core/bats-core/blob/f7defb94362f2053a3e73d13086a167448ea9133/docs/source/writing-tests.md#comment-syntax
> 
> `bats` has valid bash alternative syntax. Should we consider using it?

Sure, but not as part of this PR.

**Review by lwshang — APPROVED** [review]

**Pull request merged**
