### PR TITLE
chore: fix update-docs workflow for forked PRs

### PR DESCRIPTION
**Pull request by sesi200**
# Description

My `update-docs.yml` workflow breaks on PRs from forks (see #2490). Trying to fix this.

# How Has This Been Tested?

According to [this](https://github.com/orgs/community/discussions/26409#discussioncomment-3251818), the fix should work.

# Checklist:

- [x] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I have edited the CHANGELOG accordingly.
- [ ] I have made corresponding changes to the documentation.

### CODE REVIEW

**Review by smallstepman — APPROVED** [review]
LGTM! ✨

**Comment by smallstepman** [comment]
shall we try this out? :)

**Comment by sesi200** [comment]
It's trying in #2490 as we speak :)

**Comment by smallstepman** [comment]
@sesi200  looks like it's working now :)

fyi, in #2490 PR there was a new button in GHA/workflows section at the bottom of `conversation` tab, and it was something along these lines:
```
First-time contributors cannot run workflow before approval. 
+--------------------+
|   Approve and run  |
+--------------------+

shame I didn't think about taking a screenshot, but it looked 👌

**Comment by sesi200** [comment]
@smallstepman that had nothing to do with my changes, that's just something that appears on forks since they may contain malicious code

**Pull request merged**
