### PR TITLE
fix: Compute Motoko dependencies in linear (not exponential) time by detecting visited imports

### PR DESCRIPTION
**Pull request by crusso**
# Description

DFX invokes moc --print-deps on each canister source file to discover immediate dependencies on source files, motoko packages and canisters and then requires dfx to do a full transitive closure to discover canister dependencies. 

Unfortunately, a series of cumulative imports will lead to exponential behaviour as moc --print-deps is re-invoked on the same file multiple times.

Fixes SDK-749.

# How Has This Been Tested?

Manually tested against repro https://github.com/luc-blaeser/dfx-long-building, reducing compile times of a trivial project from an unreasonable 12s to 0.5.s. Dependencies tracing times of >2mins (!) have been observed in the wild. Hopefully this fixes that.

```
BEFORE:
crusso@vm:~/dfx-long-building$ time dfx -vvvv build
Trace mode enabled. Lots of logs coming up.
Building canisters...
No canister of type 'rust' found. Not trying to run 'cargo audit'.
Running "/home/crusso/.cache/dfinity/versions/0.11.2/moc" "/home/crusso/dfx-long-building/src/test.mo" "-o" "/home/crusso/dfx-long-building/.dfx/local/canisters/test/test.wasm" "-c" "--debug" "--idl" "--stable-types" "--public-metadata" "candid:service" "--actor-idl" "/home/crusso/dfx-long-building/.dfx/local/canisters/idl/" "--actor-alias" "test" "rrkah-fqaaa-aaaaa-aaaaq-cai" "--package" "base" "/home/crusso/.cache/dfinity/versions/0.11.2/base"...

real	0m12.765s
user	0m8.860s
sys	0m4.094s

AFTER
crusso@vm:~/dfx-long-building$ time ../sdk/target/debug/dfx -vvvv build
Trace mode enabled. Lots of logs coming up.
Building canisters...
No canister of type 'rust' found. Not trying to run 'cargo audit'.
Running "/home/crusso/.cache/dfinity/versions/0.12.0-beta.3+rev4.dirty-06a1debc/moc" "/home/crusso/dfx-long-building/src/test.mo" "-o" "/home/crusso/dfx-long-building/.dfx/local/canisters/test/test.wasm" "-c" "--debug" "--idl" "--stable-types" "--public-metadata" "candid:service" "--actor-idl" "/home/crusso/dfx-long-building/.dfx/local/canisters/idl/" "--actor-alias" "test" "rrkah-fqaaa-aaaaa-aaaaq-cai" "--package" "base" "/home/crusso/.cache/dfinity/versions/0.12.0-beta.3+rev4.dirty-06a1debc/base"...
Shrink WASM module size.

real	0m0.533s
user	0m0.494s
sys	0m0.040s

```
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Checklist:

- [x] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I have edited the CHANGELOG accordingly.
- [x] I have made corresponding changes to the documentation.

### CODE REVIEW

**Review by chenyan-dfinity — APPROVED** [review]
LGTM. This line must have been lost during some refactor somehow...

**Comment by crusso** [comment]
@chenyan-dfinity any idea why dfx compiles each moc canister twice? Once it has an ordering, I think it should be enough to just compile each canister once,  in order.

**Comment by chenyan-dfinity** [comment]
> any idea why dfx compiles each moc canister twice?

It used to twice, because we need to produce did file and wasm. Now that moc produces them at the same time, I think it only compiles once?

**Comment by crusso** [comment]
> > any idea why dfx compiles each moc canister twice?
> 
> It used to be twice, because we need to produce did file and wasm. Now that moc produces them at the same time, I think it only compiles once?

Actually, I think you are right. I was just misreading the long log with -vvvv

**Review by lwshang — APPROVED** [review]

**Comment by ericswanson-dfinity** [comment]
This will also have fixed https://dfinity.atlassian.net/browse/SDK-665.  Thanks!

**Pull request merged**
