### PR TITLE
feat: Introduce DFX_CACHE_ROOT environment variable

### LINKED ISSUE #2106: Introduce `DFX_CACHE_ROOT` instead of using `DFX_CONFIG_ROOT` for the cache directory
Introducing a new `DFX_CACHE_ROOT` environment variable would address the issue I describe in https://github.com/paulyoung/nixpkgs-dfinity-sdk/issues/4.

I imagine the change involves changing the following code, falling back to `DFX_CONFIG_ROOT` for `DFX_CACHE_ROOT ` for backwards compatibility, and adding some new tests.

https://github.com/dfinity/sdk/blob/d10f20b18790718a07af9dbc8c5a9833ccb2b83e/src/dfx/src/config/cache.rs#L69-L70

***

I'd like to make a PR but can't because of https://github.com/dfinity/sdk/issues/1955:

```
$ nix-shell --show-trace                                                         ~/projects/dfinity/sdk/main
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: program 'git' failed with exit code 128

       … while fetching the input 'git+ssh://git@github.com/dfinity-lab/common?ref=refs%2fheads%2fmaster&rev=da56c3d8094a0f2e18533b529ecb4eb8804927d1'
```

### PR DESCRIPTION
**Pull request by paulyoung**
# Description

A new environment variable, `DFX_CACHE_ROOT`, has been introduced to allow setting the cache root directory to a different location than the configuration root directory. Previously `DFX_CONFIG_ROOT` was repurposed for this which only allowed one location to be set for both the cache and configuration root directories.

The motivation for this is described in https://github.com/paulyoung/nixpkgs-dfinity-sdk/issues/4, where the cache root directory is necessarily set to a read-only directory. This means that the configuration root directory is also read-only, resulting in the error `Cannot create config directory` when trying to write `.config/dfx`

Fixes #2106 and https://github.com/paulyoung/nixpkgs-dfinity-sdk/issues/4

# How Has This Been Tested?

Only tested with `cargo test` locally. Unable to run end-to-end tests locally due to https://github.com/dfinity/sdk/issues/1955.

# Checklist:

- [x] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I have edited the CHANGELOG accordingly.
- [ ] I have made corresponding changes to the documentation.

### CODE REVIEW

**Comment by paulyoung** [comment]
Please advise on the PR title. The check failed but I used the format shown at https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with--to-draw-attention-to-breaking-change

**Comment by sesi200** [comment]
Hi Paul

Thank you very much for your PR! We would like add those changes. Annoyingly, Hydra (required part of CI, removing it is WIP) does not properly work on external PRs, so someone from the team will have to re-implement your changes and create a separate PR to merge them. This is planned for the next sprint. We'll keep you posted on the progress.

Severin

**Comment by ericswanson-dfinity** [comment]
@paulyoung Thanks for this!  The CI (internal, that you can't see) is failing in this test, when it tries to write to $HOME/.cache: https://github.com/dfinity/sdk/blob/master/src/dfx/src/lib/environment.rs#L490 . 

If you'd like to try changing this test to alter DFX_CACHE_ROOT rather than DFX_CONFIG_ROOT, it's possible that the tests will pass, and we can get this merged in right away.  Otherwise I will take care of it in our next sprint.

**Comment by ericswanson-dfinity** [comment]
@paulyoung So sorry, but it looks like there is one more place in the internal CI that needs to be changed from DFX_CONFIG_ROOT to DFX_CACHE_ROOT, here: https://github.com/dfinity/sdk/blob/master/check-binaries.nix#L18

**Review by ericswanson-dfinity — APPROVED** [review]

**Comment by paulyoung** [comment]
Please could we get a release that includes this change?

**Pull request merged**
